#!/usr/bin/env python3
"""Generate main-table JAX acceptance and cost from the original Track C results."""
import csv
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data/paper_figures/jax_original_instances.csv"
OUTPUT = ROOT / "figures/TABLE_jax_rows.tex"
METHODS = {"c_direct": "Direct LLM", "c_ivy": "Ivy",
           "c_torch2jax": r"\texttt{torch2jax}", "c_hier": "LaDiM"}
STAGES = ("execution", "numerical", "gradient_update")


def read_results(path=SOURCE):
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    if set(row["baseline_id"] for row in rows) != set(METHODS):
        raise ValueError("Expected the four original JAX methods")
    expected = {(model, stage) for model in ("cnn", "mlp") for stage in STAGES}
    for method in METHODS:
        subset = [row for row in rows if row["baseline_id"] == method]
        if (len(subset) != 6
                or {(row["model"], row["fault_layer"]) for row in subset} != expected):
            raise ValueError("Expected one JAX instance per model and fault stage")
    for row in rows:
        for field in ("strict_success", "repair_at_1"):
            if row[field] not in ("True", "False"):
                raise ValueError("Invalid JAX acceptance flag")
        if (int(row["repair_attempts"]) != 1
                or row["repair_at_1"] != row["strict_success"]
                or (row["strict_success"] == "True" and row["repair_round"] != "1")):
            raise ValueError("The original JAX results contain one attempt per instance")
        tokens = [int(row[field]) for field in
                  ("prompt_tokens", "completion_tokens", "total_tokens")]
        if min(tokens) < 0 or tokens[0] + tokens[1] != tokens[2]:
            raise ValueError("Invalid JAX token usage")
        seconds = float(row["wall_time_sec"])
        if not math.isfinite(seconds) or seconds < 0:
            raise ValueError("Invalid JAX elapsed time")
    return rows


def accepted_count(rows):
    return sum(row["strict_success"] == "True" for row in rows)


def fraction(rows):
    return f"{accepted_count(rows)}/{len(rows)}"


def build_rows(rows=None):
    rows = read_results() if rows is None else rows
    lines = ["% Generated by figures/make_jax_table.py; do not edit the numbers."]
    for method, label in METHODS.items():
        subset = [row for row in rows if row["baseline_id"] == method]
        accepted = accepted_count(subset)
        first = sum(row["repair_at_1"] == "True" for row in subset)
        tokens = sum(int(row["total_tokens"]) for row in subset)
        seconds = sum(float(row["wall_time_sec"]) for row in subset)
        cells = [label, fraction(subset), f"{100 * first / len(subset):.1f}\\%",
                 f"{tokens / accepted / 1000:.1f}K" if accepted else "n/a",
                 f"{seconds / accepted:.1f}" if accepted else "n/a"]
        if method == "c_hier":
            lines.append(r"\midrule")
            cells = [rf"\textbf{{{cell}}}" for cell in cells]
        lines.append(" & ".join(cells) + r" \\")
    lines.append(r"\bottomrule")
    return "\n".join(lines) + "\n"


def main():
    OUTPUT.write_text(build_rows(), encoding="utf-8")
    print(f"Saved: {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
