#!/usr/bin/env python3
"""Render the measured Track A methods from the current provenance index."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data/experiments/05_experiment_E_track_a_rerun/final"
OUTPUT = ROOT / "figures/TABLE_mindspore_translation_rows.tex"
METHODS = {"T-DIRECT": "Direct LLM", "T-CTE": "CodeTransEngine",
           "T-MSA": "MSAdapter", "T-HIER": "MARS"}


def read_results(source=SOURCE):
    index = json.loads((source / "run_manifest.json").read_text())
    expected = {(task, seed) for task in index["tasks"] for seed in index["seeds"]}
    if len(expected) != 15:
        raise ValueError("Expected five tasks and three seeds")
    results = {}
    source_hashes = None
    for method in METHODS:
        record = index["methods"][method]
        document = json.loads((source / record["source_summary"]).read_text())
        rows = document["rows"]
        if (len(rows) != 15 or {(r["task_id"], r["seed"]) for r in rows} != expected
                or document["method"] != method
                or document["repo_commit"] != record["repo_commit"]):
            raise ValueError(f"Mismatched Track A provenance or task grid: {method}")
        hashes = {(r["task_id"], r["seed"]): r["source_hash"] for r in rows}
        if source_hashes is not None and hashes != source_hashes:
            raise ValueError("Track A methods must use the same source programs")
        source_hashes = hashes
        for row in rows:
            for field in ("compile_success", "execution_success", "training_success", "strict_success"):
                if type(row[field]) is not bool:
                    raise ValueError(f"Missing measured status: {method}, {field}")
            if row["strict_success"] and not all(row[f] for f in
                    ("compile_success", "execution_success", "training_success")):
                raise ValueError("Verification acceptance requires completed training")
        results[method] = rows
    return results


def build_rows(results=None):
    results = read_results() if results is None else results
    lines = ["% Generated by figures/make_mindspore_translation_table.py; do not edit the numbers."]
    for method, label in METHODS.items():
        rows = results[method]
        cells = [label, *(f"{sum(row[field] for row in rows)}/{len(rows)}"
                          for field in ("training_success", "strict_success"))]
        if method == "T-HIER":
            lines.append(r"\midrule")
            cells = [rf"\textbf{{{cell}}}" for cell in cells]
        lines.append(" & ".join(cells) + r" \\")
    lines.append(r"\bottomrule")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    OUTPUT.write_text(build_rows(), encoding="utf-8")
    print(f"Saved: {OUTPUT.relative_to(ROOT)}")
